spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan/**
          filters:
            - StripPrefix=1